version: '3'

services:
  db:
    image: postgres
    container_name: mygamevault-db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    volumes:
      - vaultdata:/var/lib/postgresql/data
    restart: always
  redis:
    container_name: mygamevault-redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
    restart: always

volumes:
  vaultdata:
  redisdata:
